<?php

namespace App\Http\Resources\Order;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class MinPriceResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'error' => [
                'message' => 'Less then minimum price'
            ]
        ];
    }

    public function withResponse(Request $request, JsonResponse $response)
    {
        $response->setStatusCode(400);
        parent::withResponse($request, $response); // TODO: Change the autogenerated stub
    }

    public static $wrap = false;
}
